Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import  settings

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name="home"),
    path('blog/', include('blog.urls')),


]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)


urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .import views

app_name = 'blog'
urlpatterns = [
    path('', views.home_blog, name="home_blog"),
    path('<int:blog_id>/', views.detail, name= 'detail')
]

blog/models.py
from django.db import models
from datetime import date

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField()
    date = models.DateField()
    
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    image = models.ImageField(upload_to= 'portfolio/images/')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

# Create your views here.
def home_blog(request):
    blogs = Blog.objects.order_by('-date')[:4]
    return render(request, 'blog/home_blog.html', {'blogs':blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})  

# Create your views here.

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects = Project.objects.all()
    return  render(request,'portfolio/home.html' , {'projects':projects})
# Create your views here.

blog/templates/blog/detail.html
{% extends 'portfolio/base.html'%}
{% block content %} 
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    
<h1 class="text-center mt-5 font-weight-bold fs-2 text-info" id="blogdetailtitle">{{ blog.title }}</h1>
<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS y' }}</h5>
   
 <p class="font-weight-bold fs-5 text-warning bg-dark">{{blog.description|safe }}</p>  
   {% load static %}
 <body id="bg" style="background-image: url('{% static 'portfolio/coffee.jpg' %}');">
 </body>

    {% endblock %}

blog/templates/blog/home_blog.html
{% extends 'portfolio/base.html'%}
{% block content %} 
{% load static %}
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png"  href="{% static 'portfolio/favicon.png' %}">
    <title>Saurabh Kumar Singh</title>

    <h1 id="blogtitle" class= "font-weight-normal text-center" > My Blog </h1>


    
    {% for blog in blogs %}
     <div class= "row justify-content-center my-3">
     <div class="col-md-10">
     <a href="{% url 'blog:detail' blog.id %}">
      <h2 class="sfont-weight-bold btn btn-primary">{{ blog.title }}</h2>
     </a>
     <h5 class= "font-weight-bold ">{{ blog.date|date:'d M Y'|upper }}</h5>
     <h4 class="font-weight-bold fs-4 text-light bg-dark">{{ blog.description|striptags|truncatechars:200 }}</h4>
        </div>
    </div>
    {% endfor %}
    {% load static %}
    <body id="bg" style="background-image: url('{% static 'portfolio/cover 4.jpg' %}');">
         
    
    </body>
    {% endblock %}
     

portfolio/templates/portfolio/base.html
{% load static %}
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <link rel="icon" type="image/png"  href="{% static 'portfolio/favicon.png' %}">
    <title>Saurabh Kumar Singh</title>

    <nav class="navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">
       <img src= "{% static 'portfolio/logo.png' %}" alt="" width="245" height="50" >
 
        </a>
      </div>
    </nav>
<nav id="topNav" class= "navbar-expand-md  navbar-light">
  <div class="container">
 
    <div class="collapse navbar-collapse text-center" id="navbarNav">
  
      <ul class="navbar-nav ml-auto">
        <li>
          <a class= "navbar-brand" href= "{% url 'home' %}" ></a>
        </li>
        
        <li>
          <a role= "button" href= "{% url 'blog:home_blog' %}" class= "btn btn-primary">Blog</a>
        </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class= "container">
  {% block content %} {% endblock %}